# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: Module/mkdocs.yml

python:
  install:
    - requirements: Module/docs/requirements.txt

# Build PDF & ePub
formats: all
